copotrzebne-pl/copotrzebne-frontend

public/index.html
src/App.tsx
src/components/PageHeader.tsx
src/components/PageTitle.tsx
src/components/PanelHeader.tsx
src/contexts/types.ts
src/contexts/userContext.tsx
src/routes.tsx
src/themes/Layout.tsx
src/themes/PanelLayout.tsx
src/themes/colors.ts
src/views/Demands/components/Demand.tsx
src/views/Home/index.tsx
src/views/Panel/components/PlaceManagerPanel.tsx
src/views/Place/index.tsx

Adjust some styles, use radio buttons for priority

---

src/views/About/index.tsx

- removed unnecessary text
- justified content
- new line for "contact us"

About Us small fixes

---

src/components/TranslatedEntry.tsx
src/contexts/types.ts
src/contexts/userContext.tsx
src/views/Demands/components/Demand.tsx
src/views/Language/index.tsx
src/views/Panel/components/PlaceManagerPanel.tsx
src/views/Place/index.tsx

Add component to display dictionary entries in correct language

---

src/clients/restClient.ts

We are getting 403 status when `whoami` request is done

Redirect to homepage on 403

---

package.json
src/App.tsx
src/views/Home/index.tsx
src/views/Login/index.tsx
src/views/Place/index.tsx
yarn.lock

More info: https://github.com/nfl/react-helmet/issues/548#issuecomment-665351178

Replace helmet library with other one

---

public/index.html
src/assets/plus-icon.svg
src/components/PageHeader.tsx
src/components/PanelHeader.tsx
src/components/PlaceBox.tsx
src/themes/boxShadows.ts
src/themes/theme.ts
src/views/Demands/components/Demand.tsx
src/views/Demands/index.tsx
src/views/Home/components.tsx
src/views/Home/index.tsx
src/views/Panel/components/PlaceManagerPanel.tsx

Add small changes to things that caught my eye

---

src/components/PageHeader.tsx
src/components/PanelHeader.tsx
src/translations.ts

Add missing translations

---

src/components/PlaceBox.tsx
src/translations.ts
src/views/ManagePlace/index.tsx

- changed font colour for orgs with no ongoing collections
-  added info "no ongoing collections" on the Place Box
-  changed text for managing/editing collections from the admin panel

A few minor changes

---

robots.txt
src/views/Home/index.tsx
src/views/Place/index.tsx

- changer from relative to absolute path for og:image
- added robots.txt just in case

changed to absolute img url - trying to fix fb crawler fail

---

src/views/Panel/components/PlaceManagerPanel.tsx

- added button to organisation data edition page on the PlaceManagerPanel
- fixed typo

Added org data edition to PlaceManagerPanel

---

src/views/Demands/components/Demand.tsx

Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/58

fix: attach proper supply when demand is created from search

---

src/App.tsx
src/components/Button.tsx
src/components/forms.tsx
src/contexts/requestPlaceContext.tsx
src/contexts/types.ts
src/endpoints.ts
src/routes.tsx
src/translations.ts
src/utils/menus.ts
src/views/ManageAddress/index.tsx
src/views/Panel/components/AdminPanel.tsx
src/views/Panel/components/PlaceManagerPanel.tsx
src/views/RequestPlace/index.tsx

feat: Request new place and filter by type

---

src/contexts/types.ts
src/themes/colors.ts
src/translations.ts
src/views/Demands/components/Demand.tsx
src/views/Demands/index.tsx
src/views/ManageAddress/index.tsx
src/views/ManageDemands/index.tsx
src/views/ManagePlace/index.tsx
src/views/Panel/components/AdminPanel.tsx

and a few small tweaks, closes #77

updated button texts, category header and remove demands button

---

src/App.tsx
src/contexts/types.ts
src/views/Home/components.tsx
src/views/Place/index.tsx

API must be merged first: https://github.com/copotrzebne-pl/copotrzebne-api/pull/119
Resolves issue https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/100

Use slugs on the website to create seo links

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-pro.yml
README.md

The new deployment, next to the existing one to dev and pro.

Deployment to new AWS accounts

---

src/contexts/requestPlaceContext.tsx
src/contexts/types.ts
src/translations.ts
src/views/ManageAddress/index.tsx
src/views/Place/index.tsx

Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/113

feat: place links

---

.github/workflows/deploy-dev.yml
README.md

Is working well on: https://dev.copotrzebne.pl/

chore: Migration to one convox rack

---

src/views/Demands/components/Demand.tsx

ref: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/81

feat: add remove option to demand list

---

src/contexts/requestPlaceContext.tsx
src/contexts/types.ts
src/translations.ts
src/views/ManageAddress/index.tsx
src/views/Place/index.tsx
src/views/RequestPlace/index.tsx

ref: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/135

feat: add bank account description to place

---

src/views/Home/SupplySearch.tsx

Fix: buttons on iOS Safari

---

src/translations.ts
src/views/Demands/index.tsx
src/views/Home/index.tsx

issue: #158
Added some missing translations:
- search bar: label and placeholder
- found organisations
Ua translations approved by Nazar

Fix for missing translations

---

src/common/language.ts
src/common/types.ts
src/components/PlaceBox.tsx
src/components/forms.tsx
src/contexts/requestPlaceContext.tsx
src/contexts/types.ts
src/contexts/userContext.tsx
src/types/types.d.ts
src/views/Announcements/Announcement.tsx
src/views/Announcements/AnnouncementForm.tsx
src/views/Home/Map.tsx
src/views/Home/components.tsx
src/views/ManageAddress/index.tsx
src/views/ManageDemands/index.tsx
src/views/ManagePlace/index.tsx
src/views/Panel/components/PlaceManagerPanel.tsx
src/views/Place/index.tsx
src/views/RequestPlace/index.tsx

feat: translate place name

---

src/translations.ts
src/views/Place/components.tsx
src/views/Place/index.tsx

Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/177

feat: render links section

---

src/translations.ts

Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/179

fix: fix faq description

---

src/contexts/announcementsContext.tsx
src/types/types.d.ts
src/views/Announcements/Announcement.tsx
src/views/Announcements/AnnouncementForm.tsx

Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/181

feat: simplify public announcements

---

src/components/PageHeader.tsx
src/views/Demands/components/Demand.tsx

some styles improvements, related issues: #197 #199

fix: menu jumping issue, demands item margin

---

src/components/PlaceBox.tsx
src/views/Home/components.tsx

Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/191

fix: don't allow deleting place from home page

---

src/views/ManageDemands/index.tsx

Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/176

feat: move button for deleting all demands up

---

src/components/PageHeader.tsx
src/components/PlaceBox.tsx
src/contexts/types.ts
src/hooks/useGroupSupplies.ts
src/views/Demands/components/Demand.tsx
src/views/Home/SupplySearch.tsx
src/views/ManageAddress/index.tsx
src/views/ManageDemands/index.tsx
src/views/Panel/components/PlaceManagerPanel.tsx
src/views/Place/index.tsx

feat: new response structure for supplies
